excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://AshShields.github.io
title: Jennifer Katherine Shields
tagline: A log of everyday life
description: Advocate, artist, student.
paginate: 5